### ISSUE TITLE
Password not saved in SMPT settings

### ISSUE THREAD

**Issue by AlexsesGorodilov** [splitbrain/dokuwiki-plugin-smtp#47]
Password not saved in SMPT settings.
If the fields are filled in correctly and the test starts, SMTP issues the following log.

Set: the server
Set: the auth
Set: a message will be sent
Connecting to smtp.yandex.com at 465
Got: 220 vla1-aa6bc93a06fb.qloud-c.yandex.net (Want to use Yandex.Mail for your domain? Visit http://pdd.yandex.ru) 1654522238-ppvul2jcWW-UcMamSia
Sent: EHLO [10.10.10.234]
Got: 250-vla1-aa6bc93a06fb.qloud-c.yandex.net
Got: 250-8BITMIME
Got: 250-PIPELINING
Got: 250-SIZE 53477376
Got: 250-STARTTLS
Got: 250-AUTH LOGIN PLAIN XOAUTH2
Got: 250-DSN
Got: 250 ENHANCEDSTATUSCODES
Sent: AUTH LOGIN
Got: 334 VXNlcm5hbWU6
Sent: YWxleHNleWdvcm9kaWxvdkB5YW5kZXgucnU=
Got: 334 UGFzc3dvcmQ6
Sent: ODkyOTEwMzg1Nzc=
Got: 535 5.7.8 Error: authentication failed: Invalid user or password! 1654522238-ppvul2jcWW-UcMamSia

**Comment by frispa** [comment]
I seem to have the same problem. I get this from the SMTP-log:
=============================
Set: the server
Set: the auth
Set: a message will be sent
Connecting to smtp.gmail.com at 465
Got: 220 smtp.gmail.com ESMTP bf14-20020a0564021a4e00b0043a78236cd2sm1431651edb.89 - gsmtp
Sent: EHLO [141.138.169.224]
Got: 250-smtp.gmail.com at your service, [2a03:3c00:a002:224::1]
Got: 250-SIZE 35882577
Got: 250-8BITMIME
Got: 250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH
Got: 250-ENHANCEDSTATUSCODES
Got: 250-PIPELINING
Got: 250-CHUNKING
Got: 250 SMTPUTF8
Sent: AUTH LOGIN
Got: 334 VXNlcm5hbWU6
Sent: aGVhbHlmb2N1c2dyb2VwQGdtYWlsLmNvbQ==
Got: 334 UGFzc3dvcmQ6
Sent: Rm9jdXNvcEhlYWx5Iw==
Got: 535-5.7.8 Username and Password not accepted. Learn more at
Got: 535 5.7.8  https://support.google.com/mail/?p=BadCredentials bf14-20020a0564021a4e00b0043a78236cd2sm1431651edb.89 - gsmtp
=============================
When I check setting, the SMTP password is empty

**Comment by splitbrain** [comment]
Guys. You just posted your passwords publicly on the Internet. That warning not to do that isn't a joke.

* @AlexsesGorodilov your password is a long number
* @frispa your password tells me to focus on my health

I'm refraining from posting the actual passwords here, but getting them from your posted logs is trivial. So please change your passwords immediately.

It also tells me that your bug report is invalid since I can see that the password is saved and used to communicate with your mail server. 

Please be aware that the configuration manager will not display your saved password but will show an empty field.

**Comment by frispa** [comment]
Thanks, I saw the warning, but didn't see the password, but it is encrypted then. I will change it. Furthermore I saw that the password is saved in local.php.
Maybe this is not the right place, but can you please tell me how to set up the plugin with Gmail?
