### ISSUE TITLE
Could not open SMTP Port.

### ISSUE THREAD

**Issue by frispa** [splitbrain/dokuwiki-plugin-smtp#52]
When I try to send email using my Gmail account I get this error message: **There was an unexpected problem communicating with SMTP: Could not open SMTP Port.** 
This is the message from the SMTP log:
Set: the server
Set: the auth
Set: a message will be sent
Connecting to smtp.gmail.com at 587

I use these settings:
SMTP server: smtp.gmail.com
Port: 587
Encryption: SSL

Does it has something to do with the "Less secure app access" that has been disabled by Google?

Please help.

**Comment by frispa** [comment]
I have installed the plugin Swiftmailer now and this plugin works and sends email from my Gmail account🤷🏻‍♂️. Why isn't this working for this newer SMTP plugin?
BTW, I now get this error, but is doesn't affect the working of the plugin:
_Error loading plugin swiftmail
ParseError: syntax error, unexpected token "new"
More info is available in the error log._

**Comment by Michaelsy** [comment]
> I get this error message: There was an unexpected problem communicating with SMTP: Could not open SMTP Port.

I got the same error message when trying to send emails via the SMTP server of IONOS/1&1 (Germany).

I was able to solve the problem by making the following changes to the SMTP plugin settings:

Port 587 => 465
TLS => SSL

Other settings/combinations did not work.

Strangely enough, I did not have to make any changes to other e-mail programmes (e.g. Thunderbird), although the settings there correspond to what does not work with the SMTP plugin.

(Apparently, this problem is related to technical changes regarding the encryption methods which, according to an announcement by IONOS, will be carried out these days.)

\- Michael Sy.

**Comment by sif** [comment]
I get this error with iCloud.

**Comment by sif** [comment]
I get this error with iCloud. Gmail works though.

**Comment by splitbrain** [comment]
Nothing to do here. You need to use the correct port with the correct encryption.
